default: &default
  adapter: mysql2
  encoding: utf8
  host: localhost
  port: 3306
  reconnect: true
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default

production:
  <<: *default
